language: java
jdk:
- oraclejdk8
env:
  global:
  - ACTIVATOR_VERSION=1.3.7
  - ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE}
  - PLAY2_HOME=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal
  - SBT_EXECUTABLE_NAME=activator
  - GH_REF=github.com/theAgileFactory/maf-desktop-app
  - secure: WKGHac3SvOB2H9RcMaR8DZ9YpAcfMlNgyUGcJF45kZBitf3O2jdkNePs9U6ADR4hGHnbPyr77Fbr+PdlSxWyIwsle4jzmxcxGxc9mVznu4qY1g3c08FWzbIUXcr9mnxYbvg7qll2p9iCH0b5qD6jz2ElCoXv5J0MPXaFGGERBlvNPe0ZMOHkYOXWSJ1l8H0nRjlR/b7NuAGPsHYjRrqjCwy/Ip/53U7632H0RYYG6np/PL48qF0zGSNM0Nh3lP+PKthltf62QSfyyZEx8/2m6VGxaBEKsA1whVzCHQL3mwrkeVanzFIFcrzaVmeRXHfJge509GhYRLyOUPECv897rONOY8/4oZ7hF3ER26rDwh8xH43in81jk3d6g4WGyncCLVSEcfZZjGH9k5DkiLUf10HqbAih0UwkRL3MKS74bDUjnfaJaxPdfdp+cuCOWnwg6RISjCkSDYmgQYtz2+Rn7VjX0CeWkWvy3N9nY15FJhuspOHNQN1HJRF66zhIEtbK/Gx91/7tiSpzGN3bue9+q+gyPPG3hjOH24wNXl+0hIWq0an2Qr4SGzNOSOdULDXeKkTrkbSavPaK+Ftc7akHsUiSX5137d3NdUYLdkaSGfSGcWkprDxPFyZ4b0k5No7i3A7XQMm0he9NaXI9wlg7mo+60mvTziFl5x5KZFgPA7s=
  - secure: fExz1cUbqKVFLC2uH4rQhBicGVjI7Nwer8Vd/y771r3Vl7geC/0VuqIzIg7qBdUDSJncLn+ry9V9PlrqI7grT3pAB/2k0ept66s1byx34ut5V0nSP/rWLXQRVRa5Cm0ZiKBdHpnk293O/VF+WmP9SZo9Obgrj8/nUnV3L7C8uJ6dUqlWqaHMDuQjoljpCHr2i6xtW1tfrrEf+ejq7jBvj7N3bvBI+P6ptemkWB5nTxK4ZkryoyYdHKixyYjkZgBphfIDgtMSTBwmqecbph3JnxZfnOWIIazwWAg+t8d59AeF38bLfAMdRBeYKJdt6kGNqdIyLudOBQT9SVdS+IdvYO4ai/iEUCvJpXRvZTAMU3Uo+RSf0bfZwSm4Jsq4oXH8VTKomZvGYFRiZNOz3h6pZG4tmj65xqrGbf1LZ8UwlsG05A+5hlapQ00utUmPWZCVnPtLt3ZUR0SpS07z1AMOOe3exJjW+mQ9IIpa5VUABcHrPGRhdCfc1TsZ39+xSZvKwvng8FdkVtCkWuXmpn9AkVwdyYzufjQUkUB5ujwPMfZi1cb6PNOJz7dYmd3TYvkPlZks4nEjvTsJcQUnRwcxo4Urm0mikeme/VolEkIM38gEzLeREh+BIk7NpKJJew7OBBQk3Tl9b+74+JbN46G4JgKwTvy8i3g8qugXx+wArwY=
  - secure: eyuHrv2y9R1BFWmHtAep+1rnGLr6cKe1NzY4mwKJBz7VVOIz2jkE0DdHBKPDIi9oT9wi4rCn6b9ZewCYEXA2XCWArJp50brSWgAAIQam4XlW21MOvwM1sKXUxyK9brzVOQRyFSsdTZthlXxo1UptF0MHLIf1JlhXW0MEjtPysgpua6/h2DJLY5dXSv5YikCUVm0g877cdUus0q6o0x3NkgU95ORrQXdjj50a9VAye6q+Dnl0Z2OSHLDP6ZOwf9NQxBcmD8tBf1cDnYaAf9LvapDvdEkjiUemMhUubRd5ICeLUyJoqzRnRFq+pvEMtYHcHhPUP5tDwLXFniyuW3PbNFGnINr8dqpFi/xfok6Sp0QdA3M5aCx8cn5NAECs7Pq/cut2p//sKaN7MvbazFyjUxwFNRkjd0PP0s5+6Au9TCGBem9ktD7o0lIygYL2tK47SqRVALFRsN2TiaNINT1pavv6RkpLLPZLo4KtdYSLNjbtImMYq736kZD9Gy67MKILd35Z0nCsf+0PoVfp5QwQAwcb+EQ/lZEiYL7YGnFEi6HHvKEt58qmN3aLpY0GWRKkG7VPm+6ZTjcYyqu5k74eoY9Stt3f4Yw+Z7echasyGjQ34biwMO+U73YU3HJq99S4J/vMRC42TVIiWG87KaDabXSfpAaAPVFYoTYMfWRUhOY=
  - secure: RqyH4sENYONfAPMWgyVrKa/FX0twbegjBoOwkViVD2Q7JnyiiK/V86RhajzUz7cfGu1dDmH3f23bPxm2j/vLD5gUvn1vVF8PLuTFLnm0PCyiN2krNXB/dBaGi/s28y5+X+ZOteyaF+1vQd0ea/nwer/16SrOXq0InqEpfy57I7r5DcK6FqhDDZrMopukdYjp07Y8LBBcukSB7ga7RMA8MRLJoaJGolXN+GFsJLddwBXR+imCJqBqHnLpQp9J0R32log+OuhFiqjE5wSlSa/Hu/JCHxLVAzZaTyJM5Roj7gjCCyqbAvIuWM4zEwYk1ubGAsU019bscff4GLT5f3VckSZkK47O8rwy3E5JDY/LGWjzEgvjJ4UBfoD9YhkvIU0R+ip/OxxeYNbUK6UIZOvMYBb/yTRC/UzFNAR+JawH0RaNjFLPx4F2S8Y0t3NhYvmfWCCdC714o/DbZQE7P0/u4TuUbMYltT69MozF2po62ZDOBAjCgnynOUUNMR4tpWVWvot7H+42YGwki3tPlyP2FRED1acRi7olE/iiLqBV4RsOnR40s/kbev+dqpsDFgA71EQ8zF6CD+EbQ5T3HF9Hi4g3L9ulYj8J3kP3FaZ6cNEWJqwvp5GrbNlhr9MWrhLx+Ddl6jWCH608GhcZqJaNgpteUZUaGqCrXiioJaB/Ar8=
  - secure: T9ds3GifHThkOL5YLPHKTsPtrlWqmZb8snG+/xjiyhGhbYRhchW2QrrpGcy8iRgWNel4hnG2sLq1pR5sI3dIaTB4uKYtZWzdKVSu/l7ccBnyq++osfh9iUXTyXM/TKLBOo1Eo2Hyt/vTqJT7U8I780IXuqLoG28QizRwkiBA6YPGMxJF9u+VWRdiL4Pw3AiYdsYz52ekkGvglHLD75FcUB5xixxf+qKf4E0Xs0CMbz0aDi3W7ef0nPeLwLINbq3bqyBaDRbELrR6lk7A+07kDTcW0fuVeF1FYy0X/MpHo/+j4ASGzGHCzS23Cbp2g5Nf+6DpFxFVwO2prQKgDmeBX6uqyjx8u7ZORC+hjcISFmA11csBJNH4jGDVDVgoG2O0mMx/4MZg8trFQjnVlSSyzajgSQTvj8b7As4a5lZvHuzsa0YqtmReyOvlhFocBAhwnnslkSV8hAoxFpBt/s1TKhghmGnYVYvd8p8GVZEdgv/Y26vSQYeG6uL+FJzPIlVRd7nTU8DTMcFwAob8lRF5WsCRIQN/1hr/8+34ep7aJFAa2besX9+66j/Rq23tI34UKf9NMG0u5R2MubpC5MDLS3XhwHboP6tPNxrL7z7OGZTts5gb3+YYaMFum2PAdBvoTwlXpFz9gFOyr7PfrLssV5F3KjSXAtsL5EwMXjL105s=
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade -y oracle-java8-installer
- export SBT_OPTS="-Xms4096m -Xmx4096m -Xss4096k"
- mkdir -p ~/.gnupg
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out ~/.gnupg/secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out ~/.gnupg/pubring.gpg
  -d
- echo "<settings><servers><server><id>ossrh</id><username>\${OSSRH_JIRA_USERNAME}</username><password>\${OSSRH_JIRA_PASSWORD}</password></server></servers></settings>"
  > ~/.m2/settings.xml
install:
- wget ${ACTIVATOR_ZIP_URL}
- unzip -q ${ACTIVATOR_ZIP_FILE}
script:
- mvn -U clean install -Dgpg.passphrase="${GPG_PASSPHRASE}" --settings ~/.m2/settings.xml
after_success:
- .travis/deploy.sh
- .travis/build_dependents.sh
after_script:
- rm ~/.gnupg/secring.gpg
- rm ~/.gnupg/pubring.gpg
- rm ~/.m2/settings.xml
notifications:
  email: true
branches:
  only:
  - master
  - R16.2.3
scala:
- 2.11.8
cache:
  directories:
  - .autoconf
  - ~/.m2
  - ~/.sbt
  - ~/.ivy
